name: Build for Windows XP

on:
    push:
        branches: [ main ]
    workflow_dispatch:

jobs:
    build-xp:
        runs-on: windows-2022

        steps:
            - uses: actions/checkout@v4

            - name: Check admin rights
              shell: pwsh
              run: |
                whoami
                whoami /groups | findstr /i "Administrators"


            - name: Install v141_xp
              run: |
                & "C:\Program Files (x86)\Microsoft Visual Studio\Installer\setup.exe" modify --installPath "C:\Program Files\Microsoft Visual Studio\2022\Enterprise" --add Microsoft.VisualStudio.Component.VC.v141.x86.x64 --add Microsoft.VisualStudio.Component.VC.140 --add Microsoft.VisualStudio.Component.WinXP --quiet --norestart --channelId VisualStudio.17.Release --channelUri https://aka.ms/vs/17/release/channel

            #- name: Install Windows XP support for Visual Studio (v141_xp)
            #  shell: pwsh
            #  run: |
            #    $vsInstaller = "C:\Program Files (x86)\Microsoft Visual Studio\Installer\setup.exe"
            #    if (-not (Test-Path $vsInstaller)) {
            #      Write-Error "Visual Studio Installer not found on runner."
            #      exit 1
            #    }
            #    # productId: 根据 runner 的 VS 版本调整为 Microsoft.VisualStudio.Product.Community/Professional/Enterprise
            #    & $vsInstaller modify --productId Microsoft.VisualStudio.Product.Enterprise --add Microsoft.VisualStudio.Component.WinXP --quiet --wait --norestart
            #    if ($LASTEXITCODE -ne 0) { Write-Error "Failed to add WinXP component"; exit $LASTEXITCODE }

            #- uses: thepwrtank18/install-vs-components@main
            #  with:
            #    components: Microsoft.VisualStudio.Component.WinXP,Microsoft.VisualStudio.Component.VC.140


            - name: Verify v141_xp toolset present
              shell: pwsh
              run: |
                & "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -all -products * -requires Microsoft.VisualStudio.Component.WinXP -property installationPath || Write-Host "vswhere finished"

            - name: MSBuild for XP
              run: |
                & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\MSBuild.exe" EmptyConsoleProject\EmptyConsoleProject.sln /p:Configuration=Release /p:Platform=x86 /p:PlatformToolset=v141_xp



            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: hello
                path: EmptyConsoleProject\Release\*.exe
