name: Build for Windows XP

on:
    push:
        branches: [ main ]
    workflow_dispatch:

jobs:
    build-xp:
        runs-on: windows-2022

        steps:
            - uses: actions/checkout@v4

            - name: Install v141_xp
              run: |
                "C:\Program Files (x86)\Microsoft Visual Studio\Installer\setup.exe" modify --installPath "C:\Program Files\Microsoft Visual Studio\2022\Enterprise" --add Microsoft.VisualStudio.Component.VC.140 --add Microsoft.VisualStudio.Component.WinXP --quiet --norestart

            - name: MSBuild for XP
              run: |
                msbuild EmptyConsoleProject\EmptyConsoleProject.sln /p:Configuration=Release /p:Platform=x86

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: hello
                path: EmptyConsoleProject\Release\*.exe
